# Generated by Django 5.2.4 on 2025-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=50)),
                ('dateCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
